const {_electron:electron}=require('playwright-core');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),qa=path.resolve(root,'../../work/qa');
const dir=path.join(qa,'edges-'+Date.now());fs.mkdirSync(dir,{recursive:true});
const env={...process.env,SHINIAN_DATA_DIR:dir};delete env.ELECTRON_RUN_AS_NODE;
let app;const checks=[],errors=[];
(async()=>{
  app=await electron.launch({args:[root],env});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('.daily-quote');
  const file=path.join(dir,'library/memories.json'),read=()=>JSON.parse(fs.readFileSync(file,'utf8'));
  const exportPath=path.join(dir,'export.json');
  await app.evaluate(({dialog},filePath)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath});},exportPath);
  await page.locator('[data-action="settings"]').click();await page.locator('#export-backup').click();await page.waitForFunction(()=>document.getElementById('toast').textContent.includes('已导出'));
  assert.deepEqual(JSON.parse(fs.readFileSync(exportPath,'utf8')),read());checks.push('实际导出包含文字、图片和标签；与存储逐字段一致');
  await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]});},exportPath);
  await page.locator('#import-backup').click();await page.waitForFunction(()=>document.getElementById('toast').textContent.includes('已合并'));assert.equal(read().entries.length,6);checks.push('重复导入同一备份不产生重复条目');
  const incoming=read();incoming.entries[0].text='冲突版本内容';const conflict=path.join(dir,'conflict.json');fs.writeFileSync(conflict,JSON.stringify(incoming));
  await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]});},conflict);
  await page.locator('#import-backup').click();await page.waitForFunction(()=>document.getElementById('navigation').textContent.includes('7'));assert.equal(read().entries.length,7);
  await page.locator('#import-backup').click();await page.waitForFunction(()=>!document.getElementById('import-backup').disabled);assert.equal(read().entries.length,7);checks.push('冲突条目保留两个版本；再次导入不会重复冲突副本');
  const before=fs.readFileSync(file,'utf8');const invalid=path.join(dir,'invalid.json');fs.writeFileSync(invalid,'{"version":999}');
  await app.evaluate(({dialog},p)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[p]});},invalid);
  await page.locator('#import-backup').click();await page.waitForFunction(()=>document.getElementById('toast').textContent.includes('不是有效'));assert.equal(fs.readFileSync(file,'utf8'),before);checks.push('不合法备份被拒绝且现有文件不变');
  await page.locator('[data-close]').click();
  await page.keyboard.press('n');await page.locator('#hook').fill('未保存的引句');await page.keyboard.press('Escape');assert.equal(await page.locator('#discard-row').isVisible(),true);assert.equal(await page.locator('#hook').inputValue(),'未保存的引句');await page.locator('#keep-editing').click();await page.locator('#memory-text').fill('可以继续编辑');await page.locator('#editor-cancel').click();await page.locator('#discard').click();assert.equal(read().entries.length,7);checks.push('新建快捷键、Esc 未保存提醒、继续编辑和放弃修改');
  await page.keyboard.press('/');assert.equal(await page.locator('#search').evaluate(e=>e===document.activeElement),true);
  await page.locator('#search').fill('');await page.locator('[data-entry="seed-0"]').click();await page.locator('.lens-viewport').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('.lens-stage').evaluate(e=>e.classList.contains('lens-active')),true);await page.locator('[data-mode="full"]').click();assert.equal(await page.locator('.clear-layer').getAttribute('aria-hidden'),'false');await page.locator('[data-close]').click();checks.push('搜索快捷键、方向键透视镜与完整阅读辅助访问');
  await page.locator('[data-action="tags"]').click();await page.locator('[data-delete-tag="0"]').click();await page.locator('#confirm-ok').click();await page.waitForSelector('#add-tag-form');assert.equal(read().entries.length,7);assert.ok(read().entries.every(e=>!e.tags.includes('数学')));await page.locator('[data-close]').click();checks.push('删除标签只解除关联，不删除素材');
  await page.locator('[data-page="practice"]').click();await page.locator('#practice-count').fill('0');await page.locator('#start-practice').click();assert.equal(await page.locator('.recall-card').count(),0);
  await page.locator('[data-count="3"]').click();await page.locator('#start-practice').click();await page.locator('#end-session').click();await page.locator('#confirm-cancel').click();assert.equal(await page.locator('.recall-card').count(),1);await page.locator('#end-session').click();await page.locator('#confirm-ok').click();await page.waitForSelector('.daily-quote');assert.equal(read().entries.flatMap(e=>e.reviews).length,0);checks.push('抽查数量校验；中途退出保留选择且未答题目不计分');
  const blank={version:1,tags:[],entries:[]};const response=await page.evaluate(d=>window.shinian.save(d),blank);assert.equal(response.ok,true);
  await page.reload();await page.waitForSelector('.daily-quote');assert.ok((await page.locator('#open-daily').textContent()).includes('第一念'));await page.locator('[data-page="practice"]').click();assert.equal(await page.locator('#start-practice').isDisabled(),true);checks.push('空记忆库引导、空抽查不可启动');
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(820,640));await page.waitForFunction(()=>innerWidth<830);assert.equal(await page.evaluate(()=>document.querySelector('main').scrollWidth<=document.querySelector('main').clientWidth),true);
  const settings=await page.locator('[data-action="settings"]').boundingBox();assert.ok(settings.y+settings.height<=await page.evaluate(()=>innerHeight));checks.push('820×640 最小窗口无横向溢出，设置入口保持可见');
  assert.deepEqual(errors,[]);await app.close();fs.writeFileSync(path.join(qa,'edges-report.json'),JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks,errors},null,2));
})().catch(async e=>{console.error(e);if(app)await app.close();process.exitCode=1;});
